# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-13 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
